name: Generate Snake
on:
  # Run everyday at 6AM
  schedule:
    - cron: "0 6 * * *" 
  # Allow to manually run the workflow
  workflow_dispatch:
  push:
    branches:
    - master
jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/contribution-snake.svg?color_snake=yellow&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39
            dist/contribution-snake-dark.svg?palette=github-dark&color_snake=yellow&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}