name: 'Generate Snake'

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  generate:
    name: 'Generate and push Snake'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: 'Generate grid-snake.svg'
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/contribution-snake.svg?color_snake=orange&color_dots=#b9babd,#9be9a8,#40c463,#30a14e,#216e39
            dist/contribution-snake-dark.svg?palette=github-dark&color_snake=yellow&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Push grid-snake to the output branch'
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
